### ISSUE TITLE
Unable to run correctly

### ISSUE THREAD

**Issue by pecuna** [vdsm/virtual-dsm#126]
I got the latest version pulled before start.
I am unable to get it running and I tried with several versions of DSM. And wiping all the disks before each.
Every first time I got the "Please wait while Virtual DSM is installing..." on the ip:5000 in browser.
Which stands there for hours and nothing changes with CTRL+F5.
After a "docker restart dsm" I got the attached docker log and nothing on ip:5000
And this from nmap from the pc I am testing in browser:
```
PORT      STATE SERVICE
53/tcp    open  domain
2210/tcp  open  noaaport
12345/tcp open  netbus
```

[dsm.log](https://github.com/kroese/virtual-dsm/files/11312826/dsm.log)

**Comment by pecuna** [comment]
Host is Debian 12 with kernel 6.1.0-6-amd64
Network is macvlan.
```
kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

**Comment by zilchulant** [comment]
Maybe I can help. I do have the same or equal issues and my OS is unraid as well.
When I use the **br0** Network I get the **"Please wait while Virtual DSM is installing..."** shown and nothing changes.
br0 is a ipvlan Network which is default generated from unraid.

When I use the bridge Network I can use virtual-dsm, but as I do have ports like SMB already mapped, I want to use another IP. I cannot create a macvlan network, as with br0 I already have an ipvlan network running and it would lead to "Error response from daemon: failed to create the macvlan port: device or resource busy".

As a workaround I tried to installing virtual-dsm in bridge and then move the container to the br0 network with it's defined IP - not changing any docker config. However this always leads to not being able to reach the dashboard at all. Container Logs say "You can now login to DSM at port 5000" but the page won't load. When I use ifconfig to check if the right IP-Adress is connected, it is. I assume DSM is saving the previous IP in it's Webpage settings.

**Comment by pecuna** [comment]
I was able to get it working with the default bridge network. Didn't have the time to dig more with macvlan. Thanks. Will do it in bridge mode for now.
