### ISSUE TITLE
SN code modification parameters

### ISSUE THREAD

**Issue by kekylin** [vdsm/virtual-dsm#218]
This is a great project, thank you very much for your contribution, I would like to ask a question.
How can I change the SN code here, the SN code is zero which may cause the video in the album cannot generate the preview image, can I change it to the SN code in the official demo center of synology?

**Comment by coolspot18** [comment]
What format is the MAC in? Dash or Colons?

**Comment by lsp0701** [comment]
> You can add the following docker variables:
> 
> * HOST_SERIAL (valid Serial number of a host Synology device)
> * GUEST_SERIAL (Serial from the demo)
> * VM_NET_MAC (Mac address from demo, see Network tab)

Maybe it's a fool question: where can I get these values? @kroese

**Comment by coolspot18** [comment]
From a legit DSM instance 😂

**Comment by lsp0701** [comment]
how can I get GUEST_SERIAL, the default serial of vdsm is 0000000000
