### ISSUE TITLE
yml install not working...

### ISSUE THREAD

**Issue by intraxit** [vdsm/virtual-dsm#224]
Thank you for taking the time to create this. Great work !

I tried to install the container using the yml file on qnap nas container station and also through portainer stacks...
The install failed :
errorlog: the patch file is only an update and does not contain full dsm install files!

The run command works ok!

Maybe take a look ?

**Comment by intraxit** [comment]
No, just ran the published yml...

**Comment by intraxit** [comment]
I'm from NL !
The logs have gone as I reinstalled using the 'run' command...
The download works fine... 
The error appeared after the extraction starts and it than enter in a loop and keeps downloading the pat file 64551.
That is all the info I can provide right now...
Bye

**Comment by kissi7** [comment]
@intraxit what CPU arch is your QNAP?
I tried (yes I know it can not work due to arch) it on the raspberry pi 4 (ARM) and I got "same" error:
```
dsm  | ❯ Install: Extracting downloaded image...
dsm  | /run/install.sh: line 95: /run/extract/syno_extract_system_patch: cannot execute binary file: Exec format error
dsm  | ❯ ERROR: Invalid PAT file: File is an update pack which contains no OS image.
dsm exited with code 0
```
@kroese TIP: maybe add the CPU architecture check and warning or immediate stop the container

**Comment by intraxit** [comment]
Yep that's the error!
I'm running qnap qts on ryzen 5500u laptop in kvm vm arch x64, so should be fine!
Remember, I was able to install the container using the run command and it is working ok.
So maybe docker reports wrong arch on ryzen chip if using yml ?

**Comment by kissi7** [comment]
@kroese no, just run `docker compose up`
According to: [Multi-platform images](https://docs.docker.com/build/building/multi-platform/) it is automatic.
"When running an image with multi-platform support, docker automatically selects the image that matches your OS and architecture."

**Comment by intraxit** [comment]
@kroese  Afaik I am on the right platform (amd64), but somehow yml thinks apperantly something else..
@kissi7 Could you install kvm/qemu on raspberry pi and try it in a vm ? Interesting experiment imo...

**Comment by kissi7** [comment]
@kroese I take it back and apologize! I see I used your Dockerfile and built virtual-dsm container directly on RPi4 locally. The build process took arm arch and than I was able to start it up by docker compose up (yes I change image in docker-compose.yml to use local one). I'm sorry I confused you and you are right it should not start by default at all on different arch.

**Comment by intraxit** [comment]
@kroese 
Have you tried to run the yml in portainer or only in docker compose ?
Arm chips will become much faster very soon (Apple M2) !

**Comment by intraxit** [comment]
As mentioned the log files have disappeared as I deleted the container and reinstalled using the 'run' command. I will try again tmw and post the log files if possible...

**Comment by intraxit** [comment]
installed today using portainer stack and same error...

logs:

❯ Starting Virtual DSM for Docker v4.0...
❯ Install: Downloading installer...
❯ Install: Downloading DSM_VirtualDSM_64551.pat...
     0K ........ ........ ........ ........  9% 8.42M 36s
 32768K ........ ........ ........ ........ 18% 8.48M 32s
 65536K ........ ........ ........ ........ 28% 8.50M 29s
 98304K ........ ........ ........ ........ 37% 8.02M 25s
131072K ........ ........ ........ ........ 47% 8.46M 21s
163840K ........ ........ ........ ........ 56% 8.06M 18s
196608K ........ ........ ........ ........ 66% 8.09M 14s
229376K ........ ........ ........ ........ 75% 8.56M 10s
262144K ........ ........ ........ ........ 85% 8.02M 6s
294912K ........ ........ ........ ........ 94% 8.53M 2s
327680K ........ ........ ..               100% 8.45M=41s
❯ Install: Extracting downloaded image...
❯ ERROR: Invalid PAT file: File is an update pack which contains no OS image.
❯ Starting Virtual DSM for Docker v4.0...
❯ Install: Downloading DSM_VirtualDSM_64551.pat...
     0K ........ ........ ........ ........  9% 8.25M 37s
 32768K ........ ........ ........ ........ 18% 8.45M 33s
 65536K ........ ........ ........ ........ 28% 8.48M 29s
 98304K ........ ........ ........ ........ 37% 8.07M 25s
131072K ........ ........ ........ ........ 47% 8.51M 21s
163840K ........ ........ ........ ........ 56% 8.49M 17s
196608K ........ ........ ........ ........ 66% 8.02M 14s
229376K ........ ........ ........ ........ 75% 8.50M 10s
262144K ........ ........ ........ ........ 85% 8.46M 6s
294912K ........ ........ ........ ........ 94% 8.05M 2s
327680K ........ ........ ..               100% 8.46M=41s
❯ Install: Extracting downloaded image...
❯ ERROR: Invalid PAT file: File is an update pack which contains no OS image.
❯ Starting Virtual DSM for Docker v4.0...
❯ Install: Downloading DSM_VirtualDSM_64551.pat...
     0K ........ ........ ........ ........  9% 8.22M 37s
 32768K ........ ........ ........ ........ 18% 8.47M 33s
 65536K ........ ........ ........ ........ 28% 8.43M 29s
 98304K ........ ........ ........ ........ 37% 8.53M 25s
131072K ........ ........ ........ ........ 47% 8.50M 21s
163840K ........ ........ ........ ........ 56% 8.49M 17s
196608K ........ ........ ........ ........ 66% 7.96M 14s
229376K ........ ........ ........ ........ 75% 8.53M 10s
262144K ........ ........ ........ ........ 85% 8.45M 6s
294912K ........ ........ .....

no specific error as to why the syno_extract_system_patch is not working...

**Comment by intraxit** [comment]
There is no reason code displayed in the log as it is looping (see above log).

**Comment by intraxit** [comment]
same story on 4.03:

❯ Starting Virtual DSM for Docker v4.03...
❯ Install: Downloading DSM_VirtualDSM_64561.pat...
     0K ........ ........ ........ ........  9% 8.43M 36s
 32768K ........ ........ ........ ........ 18% 8.46M 32s
 65536K ........ ........ ........ ........ 28% 8.45M 29s
 98304K ........ ........ ........ ........ 37% 8.49M 25s
131072K ........ ........ ........ ........ 47% 8.53M 21s
163840K ........ ........ ........ ........ 56% 8.06M 17s
196608K ........ ........ ........ ........ 66% 8.47M 14s
229376K ........ ........ ........ ........ 75% 8.49M 10s
262144K ........ ........ ........ ........ 85% 8.01M 6s
294912K ........ ........ ........ ........ 94% 8.52M 2s
327680K ........ ........ .                100% 8.51M=40s
❯ Install: Extracting downloaded image...
❯ ERROR: Failed to extract PAT file, reason 255
❯ Starting Virtual DSM for Docker v4.03...
❯ Install: Downloading DSM_VirtualDSM_64561.pat...
     0K ........ ........ ........ ........  9% 8.10M 38s
 32768K ........ ........ ........ ........ 18% 8.58M 33s
 65536K ........ ........ ........ ........ 28% 8.03M 29s
 98304K ........ ........ ........ ........ 37% 8.53M 25s
131072K ........ ........ ........ ........ 47% 8.47M 21s
163840K ........ ........ ........ ........ 56% 8.08M 18s
196608K ........ ........ ........ ........ 66% 8.44M 14s
229376K ........ ........ ........ ........ 75% 8.54M 10s
262144K ........ ..

exit code 137...

If I were to guess this is probably a permissions problem...
The /storage directory is mapped to /opt/dsm on the host and has a suid bit for the group administrators.
It yml fails to extract the pat file in that directory or has no permissions to run anyway... Just my guess!

**Comment by intraxit** [comment]
If I remove the volumes: directive the yml install works ok !
So indeed a permissions error...

If I add env. variables and leave the /storage mapping:
UID=0
GID=0

0:0 is the admin user on qnap!
Extraction again failed...

What user are you using in the container to run the extraction?
Now there is probably a permission problem inside the container...confusing!

**Comment by intraxit** [comment]
If I connect the /storage volume to the exposed volume in qnap container station everything works as expected...

so:

volumes:
            - /opt/dsm:/storage

NOT working on qnap container station!

**Comment by intraxit** [comment]
The way this works on qnap is exposing a volume through qnap container station. That volume has the right permissions set for docker to be able to read/write from the container. Connecting that specific volume to the /storage directory in the container solves the permission problems.
