### ISSUE TITLE
use vDSM without KVM support?

### ISSUE THREAD

**Issue by MartinKuhl** [vdsm/virtual-dsm#401]
Hi,
I try to use this vDSM for testing reasons on my mac. There I don't have /dev/kvm.
Is it possible to use vDSM on this plattform?
In the logs I get the following message: 
`ERROR: KVM acceleration not detected (device file missing), see the FAQ about`

**Comment by MartinKuhl** [comment]
it is only for testing purposes. So thanks a lot

**Comment by MartinKuhl** [comment]
Now I see what you described....

**Comment by D4rkT1m0** [comment]
hello,
I'm stuck at kvm error, where in the compose file do you set this?
can you give an example?

> If you set `DEBUG=Y` in the compose file, it will skip the check for KVM, and it will continue.
> 
> But it will run much slower because it will not be hardware accelerated but emulated, so it might not be very useable.

**Comment by D4rkT1m0** [comment]
it's true that my first will was to have a virtual DSM into my own Synology NAS.
I didn't know that this was possible natively.

thank you
