### ISSUE TITLE
ERROR: Cannot create macvtap interface. please make sure the network type is 'macvlan' and not 'ipvlan'

### ISSUE THREAD

**Issue by gerberanub** [vdsm/virtual-dsm#415]
i am having trouble..

docker network create -d macvlan
--subnet=192.168.0.0/24
--gateway=192.168.0.1
--ip-range=192.168.0.200/29
--aux-address 'host=192.168.0.206'
-o parent=ovs_bond0 vdsm

ip link add vdsm link ovs_bond0 type macvlan mode bridge
ip addr add 192.168.0.206/32 dev vdsm
ip link set vdsm up
ip route add 192.168.0.200/29 dev vdsm

version: "3"
services:
dsm:
container_name: dsm
image: vdsm/virtual-dsm:latest
environment:
DISK_SIZE: "256G"
CPU_CORES: "1"
RAM_SIZE: "4096M"
DHCP: "Y"
devices:
- /dev/kvm
- /dev/vhost-net
device_cgroup_rules:
- 'c : rwm'
cap_add:
- NET_ADMIN
ports:
- 5000:5000
volumes:
- /volume2/docker/DSM:/storage
restart: on-failure
stop_grace_period: 1m
networks:
vdsm:
ipv4_address: 192.168.0.202

networks:
vdsm:
external: true

ERROR: Cannot create macvtap interface. please make sure the network type is 'macvlan' and not 'ipvlan'
ERROR: and that NET_ADMIN capability has been added to the container config: --cap-add NET_ADMIN

**Comment by gerberanub** [comment]
please i really need your help. i need this docker..

**Comment by xrh0905** [comment]
> I cannot read Chinese, so I have no idea what the red error message in your screenshot says.
> 
> But its possible that DuckDNS does not work when the container is in bridge-mode networking, because maybe it fails to detect the correct external IP and uses the internal IP (20.20.20.21) which cannot be reached over the internet.

While it may be off-topic, I believe this is Korean, not Chinese.
The red words in the first screenshot should be just simple "Error", the detailed error message need to be collect with SSH or Log Center.
