### ISSUE TITLE
How to use files mounted by docker?

### ISSUE THREAD

**Issue by tediorelee** [vdsm/virtual-dsm#655]
Hi, I'm tring to figure out how to use disk/files mounted by docker, I can see this via `df -h` but where can I find in DSM system/webui?

![image](https://github.com/vdsm/virtual-dsm/assets/48272067/b133f4a4-130f-4349-b0e8-4770ca6b20b7)

**Comment by GreatApo** [comment]
This has already been discussed in various issues.
Long answer short, you can't. However, there are some workarounds, see #363 (and mentioned issues).

PS: This is probably the no 1 missing feature.

**Comment by tediorelee** [comment]
> This has already been discussed in various issues. Long answer short, you can't. However, there are some workarounds, see #363 (and mentioned issues).
> 
> PS: This is probably the no 1 missing feature.

Understood, thanks for the help

**Comment by BlueFang** [comment]
希望能增加这个功能。
