### ISSUE TITLE
Any ideas howto add Surveillance Station  

### ISSUE THREAD

**Issue by MarcS1975** [vdsm/virtual-dsm#761]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

..any idea howto get the 2 default free licenses to work for a standalone server (not linked to any other Synology)?

The licenses do work on a normal Xpenology loader install.

**Comment by r0bb10** [comment]
> I understand. But Xpenology with Host Loader ( not docker) comes with 2 free surveillance licenses. Why are they not in the docker version?

no, it's not xpenology that comes with free licenses, that is synology who gives 2 licenses included in the product (or 8, depending on the product).. xpenology is just a loader for dsm, so it's normal that it has the same number of licenses.

> But vDSM is based on Xpenology DSM. Isn't it?

the loaders used in the xpenology dsm patch and shim the software to make it run, and it's based on x86.. this project uses the stock pat and nothing is modified, and the build il kvmx64.. so, as kroese sais, nothing in common.
