### ISSUE TITLE
VDSM - Did not start after updating to 7.15

### ISSUE THREAD

**Issue by Masterciw** [vdsm/virtual-dsm#773]
### Operating system

docker lxc container under latest proxmox version

### Description

Hello,

after updating to vfsm 7.15 last night the container did not come up. The following lines are logged.
This is running in an infinite loop.

Rolling back to version 7:14 manually is working as desired and everything comes up as normal.

In the moment i've no plan what happend here and any help would be useful for me. 

Thanks

### Docker compose

services:
    dsm:
        image: vdsm/virtual-dsm:latest
        hostname: synology
        container_name: synology
        environment:
            DISK_SIZE: "768G"
            ALLOCATE: "N"
            CPU_CORES: "2"
            RAM_SIZE: "2048M"
            DHCP: "Y"
            DEBUG: "N"

            VM_NET_MAC: "xx-xx-xx-xx-xx-xx" 
            HOST_SERIAL: "xxxxxxxxxxxxxxx"
            GUEST_SERIAL: "xxxxxxxxxxxxxxx"
            HOST_MAC: "xx-xx-xx-xx-xx-xx"
            HOST_MODEL: "DSxxxx+" 
        labels:
          com.centurylinklabs.watchtower.enable: true 
        networks:
            vdsm:
                ipv4_address: yyy.yyy.yyy.yyy
        devices:
            - /dev/kvm
            - /dev/vhost-net
        cap_add:
            - NET_ADMIN
        volumes:
            - /synology:/storage
        restart: unless-stopped
        stop_grace_period: 1m
        device_cgroup_rules:
            - 'c *:* rwm'

networks:
    vdsm:
        external: true

### Docker log

❯ Warning: unexpected clocksource: kvm-clock
❯ Booting Virtual DSM using QEMU v8.2.4...
❯ ERROR: qemu-system-x86_64: -netdev tap,id=hostnet0,vhost=on,vhostfd=40,fd=30,script=no,downscript=no: ifname=, script=, downscript=, vnet_hdr=, helper=, queues=, fds=, and vhostfds= are invalid with fd=
❯ Starting Virtual DSM for Docker v7.15...
❯ For support visit https://github.com/vdsm/virtual-dsm
❯ CPU: Intel Core TM i5 6500T CPU | RAM: 4/5 GB | DISK: 303 GB (ext4) | HOST: 5.15.0-112...

**Comment by Masterciw** [comment]
Yes, of course, you're right. After updating the stack via the portainer tool with reloading the source image again it works like desired.

Initial the stack was updated automatically via watchtower at 3:55 UTC time.

So everyone outside with the same problem. The solution in this case is:

- Stop the stack with
  docker-compose down
- Start the stack again and force recreate
  docker-compose up -d --force-recreate
- Cleanup danging image with e.g. (Attention, this will clean all dangling images)
  docker rmi $(docker images -f "dangling=true" -q) -f


A bit easier it is via portainer management tool.
- Navigate to the desired stack and go to the edit mode
- Scroll down until you see the button: "Update the stack", click on it.
- In the popup window put the slider "Re-pull image and redeploy" to on and click on "Update"

This is doing nearling the same as the above docker-compose commands except cleaning up the dangling images

Have a nice day and thank you very much for your help.
Greetings from germany.

Michael

**Comment by JiweiMaster** [comment]
hi bro, how can you set HOST_SERIAL and GUEST_SERIAL?

> ### Operating system
> docker lxc container under latest proxmox version
> 
> ### Description
> Hello,
> 
> after updating to vfsm 7.15 last night the container did not come up. The following lines are logged. This is running in an infinite loop.
> 
> Rolling back to version 7:14 manually is working as desired and everything comes up as normal.
> 
> In the moment i've no plan what happend here and any help would be useful for me.
> 
> Thanks
> 
> ### Docker compose
> services: dsm: image: vdsm/virtual-dsm:latest hostname: synology container_name: synology environment: DISK_SIZE: "768G" ALLOCATE: "N" CPU_CORES: "2" RAM_SIZE: "2048M" DHCP: "Y" DEBUG: "N"
> 
> ```
>         VM_NET_MAC: "xx-xx-xx-xx-xx-xx" 
>         HOST_SERIAL: "xxxxxxxxxxxxxxx"
>         GUEST_SERIAL: "xxxxxxxxxxxxxxx"
>         HOST_MAC: "xx-xx-xx-xx-xx-xx"
>         HOST_MODEL: "DSxxxx+" 
>     labels:
>       com.centurylinklabs.watchtower.enable: true 
>     networks:
>         vdsm:
>             ipv4_address: yyy.yyy.yyy.yyy
>     devices:
>         - /dev/kvm
>         - /dev/vhost-net
>     cap_add:
>         - NET_ADMIN
>     volumes:
>         - /synology:/storage
>     restart: unless-stopped
>     stop_grace_period: 1m
>     device_cgroup_rules:
>         - 'c *:* rwm'
> ```
> 
> networks: vdsm: external: true
> 
> ### Docker log
> ❯ Warning: unexpected clocksource: kvm-clock ❯ Booting Virtual DSM using QEMU v8.2.4... ❯ ERROR: qemu-system-x86_64: -netdev tap,id=hostnet0,vhost=on,vhostfd=40,fd=30,script=no,downscript=no: ifname=, script=, downscript=, vnet_hdr=, helper=, queues=, fds=, and vhostfds= are invalid with fd= ❯ Starting Virtual DSM for Docker v7.15... ❯ For support visit https://github.com/vdsm/virtual-dsm ❯ CPU: Intel Core TM i5 6500T CPU | RAM: 4/5 GB | DISK: 303 GB (ext4) | HOST: 5.15.0-112...
> 
> ### Screenshots (optional)
> _No response_

**Comment by Masterciw** [comment]
Hello JiweiMaster,
hello all other who are interested in setting host and guest serial.

i followed this forum thread:
[](https://github.com/vdsm/virtual-dsm/issues/266)

In my case i really own a physical DS1815+ Synology NAS Device with 8 bays.
The virtual one is always on running as docker container for using Synology Photos.
I wanted to add Advanced Media Extensions and this is only possible with an valid synology account and with
the additional information in the docker container. On my physical NAS i already installed the media extensions.
I'm using this solution because the 8-bay NAS is consuming a lot of power and was running all the time (except sleepmode in the night). Now i upload photos to the virtuals synology and view them from there and when physical NAS is online the photos are synced via synology drive share sync. My homeserver is consuming only 15W and is hosting many docker services around the clock. So i save a lot of money every year.

Most of the needed information you can find here:
[](https://finds.synology.com/#) 

        VM_NET_MAC: "xx-xx-xx-xx-xx-xx"        # Via link above   
        HOST_SERIAL: "xxxxxxxxxxxxxxx"           # Via link above
        GUEST_SERIAL: "xxxxxxxxxxxxxxx"          # In the webgui under Info-Center inside the virtual DSM
        HOST_MAC: "xx-xx-xx-xx-xx-xx"            # In the webgui under Info-Center inside the network tab of the physical NAS
        HOST_MODEL: "DSxxxx+"                      # In the webgui under Info-Center

That it. I'll hope this information is enough to answer your question and to help you fulfil your requirements.

Sincerly Michael


P.S. If you don't own a physical synology nas, it is maybe a way to by a used one from ebay for a few bucks and use the information from this device.
