### ISSUE TITLE
[Question]: Networking

### ISSUE THREAD

**Issue by toxic0berliner** [vdsm/virtual-dsm#779]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

I feel I'm slowly discovering how virtualDSM networking works...

It seems to me I cannot pass more than 1 ethernet interface to the container.
I'm running this inside an LXC on my ProxMox, so in order for DSM to get it's own IP, I need :
- 1 ip for my LXC (debian12) running docker
- 1 IP for the virtualDSM container, defined in the docker compose file, serving the virtualDSM nging showing boot progress
- 1 IP for DSM itslf that it'll use DHCP on.

I had setup my router dhcp to give out the same IP to DSM as the one I gave to virtualDSM in the compose file, seems like a bad idea in the end...

Fact is I have 2 VLANs in which I'll need access to my NAS, my former physical syno having 2 physical NIC and therefore that was no issue for me.
Now I'm facing speed issues between my vlans, something I'll solve otherwise, but I'd have liked for someone to confirm me that
- **indeed I need 3 distinct IPs in my setup for each of the above**
- **there is no easy way with virtualDSM to pass it several network interfaces**

I have long heard that docker networking is... well... people complain about it ;)
So seems to me I can't easily take advantage of my PVE actually having an openvswitch switch supporting all VLANs I need and simply pass one or several NIC from it up to DSM...

Note that from an LXC on my VLAN "plugged" directly onto the openvSwitch Switch, up to DSM through the macvlan and therefore the eth0 of my virtualDSM-LXC itself "plugged" into the same openvSwitch Switch I do get 12GB/s of throughput, so well enough for me !

But reserving 3 IPs seems a shame as I wasn't anticipating managing 3 machines... 
Plus not having several NIC inside DSM forces me to find and solve my issue that is throtteling inter-VLAN networking to 1GB/s... That was an issue I planned to leave for another time ;)

Thanks in advance for your kind answer to the above 2 questions.

If I may add, now that I understand virtualDSM is running qemu inside a docker container, do you know of a fork or intend to provide a (debian) native way of running qemu, bypassing the docker stuff, and letting dumb guys like me tweak qemu settings to pass several network interfaces for example ? (meaning taking what's inside the docker image and running it locally..., saying that I probably think I could read the dockerfile and do it myself :D )

**Comment by mndti** [comment]
Use qemu directly and you can use as many lan as you want: https://github.com/vdsm/virtual-dsm/issues/674

**Comment by toxic0berliner** [comment]
Yeah got it working with qemu just fine with as many NICs as I want thanks.
