### ISSUE TITLE
[Question]: Possible using DD diskimages to mount a (real) Synology RAID10 volume ?

### ISSUE THREAD

**Issue by dumpbox76** [vdsm/virtual-dsm#838]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

I have a Synology DS920+ here that got an unmountable BTFRS RAID10 volume of 4 disks. The data on it is a bit important (no recent backup). The volume got unmountable because the SSD cache removal bugged out and didn't report its completion to DSM. (so it's expecting a SSD cache that isn't there)

While there are some command line tools that probably can fix this issue, there is always a danger to make things worse.

Therefor, I was wondering. Could I DD those 4 harddrives into 4 IMG files, store them on a unRAID ZFS dataset volume, and get them mounted in Virtual DSM ?

My reason, on the ZFS dataset i can create snapshots of the IMG files. So I can go start trying to repair the volume in Virtual DSM, and if it doesn't work out, or make things worse, I can revert the snapshot and try again.

**Comment by dumpbox76** [comment]
Ah ok, that rules out virtual DSM as potential recovery platform. Thank you for you answer!

**Comment by mniewiera** [comment]
@dumpbox76 did you manage to find a solution? i'm in a similar situation. My 1511+ died and the disks aren't mountable the way they are. i thought i'll try something like you and use virtual-dsm as a recovery platform.
