### ISSUE TITLE
How to configure vDSM to support https and Let's Encrypt

### ISSUE THREAD

**Issue by ChengYen-Tang** [vdsm/virtual-dsm#852]
### Operating system

Fedora 41

### Description

Hi,
I'm trying to use Let's Encrypt to obtain an SSL certificate, but it always fails. Then I found that except Http:5000, other Http80, Http443, and Http5001 did not work.

Is there any setting error on my part?

### Docker compose

```
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:latest
        environment:
            DISK_SIZE: "2T"
            RAM_SIZE: "8G"
            CPU_CORES: "6"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
            - 5001:5001
            - 80:80
            - 443:443
        volumes:
            - /mnt/data:/storage
        stop_grace_period: 2m
```

### Docker log

❯ Starting Virtual DSM for Docker v7.20...
❯ For support visit https://github.com/vdsm/virtual-dsm
❯ CPU: AMD EPYC 7513 32 Core Processor | RAM: 8/10 GB | DISK: 8186 GB (btrfs) | HOST: 6.11.7-300.fc41.x86_64...

iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
❯ ERROR: The 'ip_tables' kernel module is not loaded. Try this command: sudo modprobe ip_tables iptable_nat
❯ Warning: falling back to usermode networking! Performance will be bad and port forwarding will not work.
❯ Warning: your configured RAM_SIZE of 8 GB is very close to the 8 GB of memory available, please consider a lower value.
❯ Booting Virtual DSM using QEMU v9.1.0...

...

[    0.625640] Failed to access perfctr msr (MSR c0010007 is 0)

...

------------upgrade
Begin upgrade procedure
e2fsck 1.44.1 (24-Mar-2018)
/sbin/e2fsck: No such file or directory while trying to open /dev/sda3
mount: mounting /dev/sda3 on /tmpData failed: No such file or directory
umount: can't unmount /tmpData: Invalid argument
[   11.706526] loop: module loaded
Failed to found any patch

...

[   17.559185] systemd[1]: Cannot add dependency job for unit pkg-install-low-priority-builtin.service, ignoring: Unit pkg-install-low-priority-builtin.service failed to load: No such file or directory.
[   17.569216] systemd[1]: Cannot add dependency job for unit pkg-synorelayd-reload-fixed-package-config.service, ignoring: Unit synorelayd.service failed to load: No such file or directory.
[   17.579790] systemd[1]: Cannot add dependency job for unit pkg-synorelayd-reload-package-config.service, ignoring: Unit synorelayd.service failed to load: No such file or directory.
[   17.589218] systemd[1]: Cannot add dependency job for unit pkg-install-high-priority-builtin.service, ignoring: Unit pkg-install-high-priority-builtin.service failed to load: No such file or directory.

...

[DEPEND] Dependency failed for agetty for console output([   18.067179] qede_init: QLogic FastLinQ 4xxxx Ethernet Driver qede 8.33.9.0
for vDSM).
[   18.071761] systemd[1]: Dependency failed for agetty for console output(for vDSM).
[   18.076372] systemd[1]: Job vdsm_dummy_tty.service/start failed with result 'dependency'.

...

[FAILED] Failed to start Adjust NIC sequence.
See "systemctl status SynoInitEth.service" for details.

...

[FAILED] Failed to start Mount usb fs.
See "systemctl status syno-mount-usbfs.service" for details.

...

[DEPEND] Dependency failed for rebuild local user and group db.

...

[FAILED] Failed to start synoindex check if ... any synoindex-related packages.
See "systemctl status synoindex-checkpackage.service" for details.
[DEPEND] Dependency failed for synoindex scand.
[DEPEND] Dependency failed for synoindex workerd.
[DEPEND] Dependency failed for synomkflvd.
[DEPEND] Dependency failed for synoindexd.
[DEPEND] Dependency failed for synomkthumbd.
[DEPEND] Dependency failed for synoindex plugind.
[DEPEND] Dependency failed for synoindex mediad.
[DEPEND] Dependency failed for synoindex notifyd.

...

[FAILED] Failed to start Check Nic on extern...lot is synology nic but unprobe.
See "systemctl status syno-nic-supported-check.service" for details.

...

Synology login: [   26.269811] findhostd uses obsolete (PF_INET,SOCK_PACKET)
[   26.366424] fuse init (API version 7.23)
[   27.170603] Synotify use 16384 event queue size

❯ -----------------------------------------------------------
❯  You can now login to DSM at port 5000
❯ -----------------------------------------------------------

[   38.386701] Synotify use 16384 event queue size
[   38.389411] Synotify use 16384 event queue size

[Full docker logs.txt](https://github.com/user-attachments/files/17787383/Full.docker.logs.txt)

**Comment by waxi-i** [comment]
Because your service does not listen to port 80 443, port 5001 to see if you need to configure the certificate after the visit

**Comment by ChengYen-Tang** [comment]
Hi @kroese ,
Do you know what causes this?
Do I need to set user: root in docker compose file?

> The problem is
> 
> ```
> ERROR: The 'ip_tables' kernel module is not loaded. Try this command: sudo modprobe ip_tables iptable_nat
> ❯ Warning: falling back to usermode networking! Performance will be bad and port forwarding will not work.
> ```
> 
> Without it, port mapping any ports other than 5000 will not work.

![image](https://github.com/user-attachments/assets/bc83dedb-e5d6-42fe-87ef-64fae84906ba)

**Comment by ChengYen-Tang** [comment]
It worked.
Thanks
