### ISSUE TITLE
On a real Synology...

### ISSUE THREAD

**Issue by calimansi** [vdsm/virtual-dsm#94]
The docker image will download everything correctly, then start spitting this out in the log:

Starting Virtual DSM for Docker v3.40...
Install: Downloading extractor...
Install: Downloading DSM_VirtualDSM_64216.pat...
     0K ........ ........ ........ ........  9% 36.6M 8s
 32768K ........ ........ ........ ........ 18% 31.1M 8s
 65536K ........ ........ ........ ........ 28% 43.1M 7s
 98304K ........ ........ ........ ........ 37% 47.3M 5s
131072K ........ ........ ........ ........ 47% 54.2M 4s
163840K ........ ........ ........ ........ 56% 55.7M 3s
196608K ........ ........ ........ ........ 66% 60.3M 3s
229376K ........ ........ ........ ........ 75% 57.3M 2s
262144K ........ ........ ........ ........ 85% 62.0M 1s
294912K ........ ........ ........ ........ 94% 58.7M 0s
327680K ........ ........ .                100% 53.0M=7.0s
Install: Extracting downloaded image...
Install: Allocating diskspace...
Install: Creating partition table...
Install: Extracting system partition...
Install: Installing system partition...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Starting Virtual DSM for Docker v3.40...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.

**Comment by tabris233** [comment]
hi~ @kroese I meet the same problem. I already try v3.41, it work fine!  Very very thanks you.

**Comment by calimansi** [comment]
This is what I get now:

```
Starting Virtual DSM for Docker v3.42...
Install: Downloading extractor...
Install: Downloading DSM_VirtualDSM_64216.pat...
     0K ........ ........ ........ ........  9% 47.2M 6s
 32768K ........ ........ ........ ........ 18% 59.7M 5s
 65536K ........ ........ ........ ........ 28% 62.5M 4s
 98304K ........ ........ ........ ........ 37% 60.1M 4s
131072K ........ ........ ........ ........ 47% 58.4M 3s
163840K ........ ........ ........ ........ 56% 51.8M 3s
196608K ........ ........ ........ ........ 66% 51.3M 2s
229376K ........ ........ ........ ........ 75% 53.4M 1s
262144K ........ ........ ........ ........ 85% 58.6M 1s
294912K ........ ........ ........ ........ 94% 56.4M 0s
327680K ........ ........ .                100% 58.0M=6.1s
Install: Extracting downloaded image...
Install: Allocating diskspace...
Install: Creating partition table...
Install: Extracting system partition...
Install: Installing system partition...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
pidwait: pidfd_open() not implemented in Linux < 5.3
Starting Virtual DSM for Docker v3.42...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
pidwait: pidfd_open() not implemented in Linux < 5.3
Starting Virtual DSM for Docker v3.42...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
pidwait: pidfd_open() not implemented in Linux < 5.3
Starting Virtual DSM for Docker v3.42...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
pidwait: pidfd_open() not implemented in Linux < 5.3
Starting Virtual DSM for Docker v3.42...
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
pidwait: pidfd_open() not implemented in Linux < 5.3``
```

**Comment by calimansi** [comment]
That's money doode!!

Its booting now.  Magic.

**Comment by calimansi** [comment]
I'm thinking the initial boot takes a while...

**Comment by calimansi** [comment]
Actually, I can't connect.  The log says I can connect to 5000, I have it mapped to 6000.  When I try to connect on port 6000, my browser says there's nothing.  I think that iptables thing is important.

**Comment by calimansi** [comment]
I am using my real dsm s IP with :6000 on the end. I have other services running on there like frigate and deluge and I can connect just fine.

**Comment by calimansi** [comment]
OMG... I got it to work.  Word of wisdom... don't use port 6000... I guess browsers don't like it.

[List of other ports not to use.](https://neo4j.com/developer/kb/list-of-restricted-ports-in-browsers/)
